### ISSUE TITLE
facing issues when using in AWS lambda

### ISSUE THREAD

**Issue by sosimtechvaibhav** [dichovsky/pdf-to-png-converter#26]
```
{
  "errorType": "Error",
  "errorMessage": "/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/nodejs/node_modules/canvas/build/Release/libpng16.so.16)",
  "trace": [
    "Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/nodejs/node_modules/canvas/build/Release/libpng16.so.16)",
    "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    "    at Module.require (internal/modules/cjs/loader.js:974:19)",
    "    at require (internal/modules/cjs/helpers.js:101:18)",
    "    at Object.<anonymous> (/opt/nodejs/node_modules/canvas/lib/bindings.js:3:18)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"
  ]
}
```

Created custom layer from Linux machine.

**Comment by dichovsky** [comment]
Probably this will help

https://github.com/Automattic/node-canvas/wiki/Installation:-AWS-Lambda
